-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 05, 2025 at 10:11 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bandienthoai`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `product_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL,
  `sell_quantity` int(11) NOT NULL DEFAULT 0,
  `price` int(11) NOT NULL,
  `sale_price` int(11) NOT NULL,
  `create_date` datetime NOT NULL DEFAULT current_timestamp(),
  `views` int(11) NOT NULL DEFAULT 0,
  `details` text NOT NULL,
  `short_description` text NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_id`, `category_id`, `name`, `image`, `quantity`, `sell_quantity`, `price`, `sale_price`, `create_date`, `views`, `details`, `short_description`, `status`) VALUES
(1, 2, 'Điện thoại Redmi 12 8GB/128GB', 'redmi.jpg', 30, 0, 3500000, 3190000, '2025-05-08 08:22:03', 15, '<p><strong>Nếu bạn vẫn luôn nghĩ rằng một chiếc điện thoại giá rẻ không thể mang lại trải nghiệm tốt thì nhất định bạn phải xem qua Redmi 12 8GB/128GB.</strong></p>\r\n<p>Có thể bạn chưa biết, **Redmi 12** là một trong những smartphone nổi bật nhất trong phân khúc tầm trung của Xiaomi trong năm 2024, nhờ thiết kế tinh tế, màn hình lớn và hiệu năng vượt mong đợi. Không chỉ vậy, mẫu điện thoại này cũng được nhiều reviewer công nghệ đánh giá là “sự lựa chọn hoàn hảo cho học sinh – sinh viên” với cấu hình RAM 8GB, bộ nhớ trong 128GB cùng vi xử lý MediaTek Helio G88. Và đây cũng chính là mẫu điện thoại mà anh <strong>Hoàng N.Trung</strong> (Section Manager - VEU) đã “highly recommend” trong buổi chia sẻ về “Smartphone dưới 4 triệu đáng mua” ngày 28/4, bởi theo anh đây là <i><strong>“một chiếc máy quá ổn trong tầm giá, đủ dùng cho học tập, giải trí, và thậm chí cả chơi game nhẹ.” </strong></i>Giờ cùng khám phá chi tiết chiếc điện thoại này nhé!</p>\r\n', '<p>Hãng sản xuất: <strong>Xiaomi</strong> &nbsp; &nbsp; &nbsp;Model: <strong>Redmi 12 8GB/128GB</strong></p>\r\n', 1),
(2, 2, 'IPhone 14 Trắng 1TB', 'iphone3.jpg', 40, 0, 22500000, 20190000, '2025-04-08 10:15:54', 10, '<p><strong>Nếu bạn nghĩ rằng iPhone chỉ dành cho những ai muốn \"khoe mẽ\" thì có thể bạn chưa thật sự hiểu được đẳng cấp của iPhone 14 phiên bản Trắng 1TB.</strong></p>\r\n<p>Có thể bạn chưa biết, <strong>iPhone 14</strong> không chỉ là một bản nâng cấp về phần cứng mà còn là bước tiến mạnh mẽ về trải nghiệm người dùng. Với phiên bản bộ nhớ 1TB, người dùng hoàn toàn có thể lưu trữ hàng ngàn bức ảnh chất lượng cao, video 4K dài hàng giờ đồng hồ mà không cần lo hết dung lượng. Không chỉ vậy, thiết kế mặt lưng kính cường lực cùng khung viền nhôm cao cấp tạo nên vẻ ngoài tinh tế, đẳng cấp – đặc biệt là với phiên bản màu Trắng thanh lịch.</p>\r\n<p>Chiếc máy này cũng là sự lựa chọn của anh <strong>Hoàng N.Trung</strong> (Section Manager - VEU), người từng chia sẻ trong buổi Talk về \"Thiết bị tối ưu cho công việc sáng tạo\" ngày 28/4 rằng đây là <i><strong>\"chiếc điện thoại giúp tôi quay dựng video chất lượng cao, xử lý nhanh mà không cần dùng đến laptop khi di chuyển\".</strong></i> Với chip A15 Bionic mạnh mẽ, camera cải tiến và dung lượng khủng, iPhone 14 Trắng 1TB thực sự là công cụ lý tưởng cho người dùng chuyên nghiệp. Cùng khám phá thêm chi tiết bên dưới nhé!</p>\r\n', '<p>Hãng sản xuất: <strong>Apple</strong> &nbsp; &nbsp; &nbsp;Model: <strong>iPhone 14</strong> &nbsp; &nbsp; &nbsp;Màu sắc: <strong>Trắng</strong> &nbsp; &nbsp; &nbsp;Dung lượng: <strong>1TB</strong></p>\r\n', 1),
(6, 2, 'Samsung Galaxy M54 8GB/256GB Màu Bạc', 'samsung1.jpg', 35, 0, 8990000, 5990000, '2025-05-08 22:23:49', 2, '<p><strong>Nếu bạn cho rằng chỉ dòng flagship mới sở hữu hiệu năng mạnh và pin “trâu” thì có lẽ bạn chưa từng trải nghiệm Galaxy M54 5G.</strong></p>\r\n<p>Có thể bạn chưa biết, <strong>Samsung Galaxy M54 5G</strong> là một trong những chiếc smartphone nổi bật trong phân khúc tầm trung cao cấp của Samsung năm 2024, gây ấn tượng nhờ hiệu năng mạnh mẽ với Exynos 1380, RAM 8GB cùng bộ nhớ trong 256GB – tha hồ lưu trữ phim, ảnh và ứng dụng. Không chỉ vậy, viên pin khủng 6000mAh kết hợp sạc nhanh 25W giúp máy hoạt động bền bỉ suốt ngày dài mà không lo gián đoạn.</p>\r\n<p>Đây cũng là chiếc điện thoại mà anh <strong>Hoàng N.Trung</strong> (Section Manager - VEU) đã giới thiệu trong buổi chia sẻ về “Smartphone hiệu năng cao cho công việc lẫn giải trí” ngày 28/4, với nhận định: <i><strong>“Chiếc M54 này là một lựa chọn rất cân bằng – cấu hình tốt, pin khỏe, màn hình đẹp, giá lại mềm.”</strong></i> Hãy cùng khám phá thêm lý do vì sao Galaxy M54 5G lại được yêu thích đến vậy!</p>\r\n', '<p>Hãng sản xuất: <strong>Samsung</strong> &nbsp; &nbsp; &nbsp;Model: <strong>Galaxy M54 5G</strong> &nbsp; &nbsp; &nbsp;Màu sắc: <strong>Sliver (Bạc)</strong> &nbsp; &nbsp; &nbsp;Dung lượng: <strong>8GB/256GB</strong></p>\r\n', 1),
(14, 17, 'Pin sạc dự phòng Polymer 10.000 mAh 12W AVA+ PJ JP192', 'sacduphong1.jpeg', 10, 0, 380000, 150000, '2025-05-08 22:54:49', 0, '<p><strong>Nếu bạn đang tìm kiếm một pin sạc dự phòng mỏng nhẹ, an toàn và tiện lợi thì AVA+ PJ JP192 là một lựa chọn sáng giá.</strong></p>\r\n<p>Với dung lượng 10.000mAh cùng công nghệ sạc 12W ổn định, sản phẩm này phù hợp cho hầu hết các dòng điện thoại thông minh hiện nay. Thiết kế nhỏ gọn, vỏ ngoài nhám giúp cầm chắc tay, dễ mang theo bên mình. Dòng sạc ra ổn định giúp bảo vệ thiết bị không bị quá nhiệt hay quá dòng.</p>\r\n<p>Theo đánh giá từ anh <strong>Hoàng N.Trung</strong> trong buổi tư vấn \"Chọn sạc dự phòng an toàn – giá tốt\", thì: <i><strong>“AVA+ PJ JP192 là lựa chọn rất hợp lý cho học sinh – sinh viên hoặc người dùng phổ thông, vừa túi tiền mà vẫn an tâm về chất lượng.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>AVA</strong> &nbsp; &nbsp; &nbsp;Model: <strong>PJ JP192</strong> &nbsp; &nbsp; &nbsp;Dung lượng: <strong>10.000 mAh</strong> &nbsp; &nbsp; &nbsp;Công suất: <strong>12W</strong></p>\r\n', 1),
(15, 17, 'Pin sạc dự phòng HePu MP912 10.000mAh', 'sacduphong2.jpg', 20, 0, 350000, 280000, '2025-05-08 23:05:47', 1, '<p><strong>HePu MP912 là mẫu sạc dự phòng thiết kế tối giản nhưng đầy hiệu quả, đáp ứng tốt nhu cầu sử dụng cơ bản hàng ngày.</strong></p>\r\n<p>Sở hữu dung lượng 10.000mAh, MP912 đủ sức sạc đầy 1-2 lần cho hầu hết các smartphone hiện nay. Vỏ nhựa ABS bền bỉ, thiết kế bo tròn dễ cầm, tích hợp 2 cổng ra USB tiện lợi để sạc cùng lúc nhiều thiết bị.</p>\r\n<p>Chia sẻ trong chuyên đề “Đánh giá pin dự phòng phổ thông”, anh <strong>Bùi Quang Dũng</strong> đánh giá: <i><strong>“MP912 có hiệu năng ổn định, ít nóng, dùng tốt cho cả người lớn tuổi hoặc học sinh cần thiết bị dễ dùng.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>HePu</strong> &nbsp; &nbsp; &nbsp;Model: <strong>MP912</strong> &nbsp; &nbsp; &nbsp;Dung lượng: <strong>10.000 mAh</strong></p>\r\n', 1),
(16, 17, 'Sạc dự phòng Pisen Mini Power 10000mAh', 'sacduphong3.jpg', 30, 0, 880000, 680000, '2025-05-08 23:09:13', 10, '<p><strong>Nếu bạn cần một chiếc sạc dự phòng nhỏ gọn, đẹp mắt và có thương hiệu uy tín thì Pisen Mini Power là lựa chọn không thể bỏ qua.</strong></p>\r\n<p>Sản phẩm có thiết kế siêu nhỏ gọn, trọng lượng nhẹ nhưng vẫn đảm bảo dung lượng sạc lên đến 10.000mAh, dễ dàng mang theo trong túi xách, balo. Tích hợp các công nghệ bảo vệ thông minh như chống quá nhiệt, chống đoản mạch giúp an toàn cho cả người dùng và thiết bị.</p>\r\n<p>Trong buổi giới thiệu “Phụ kiện đáng mua dịp lễ”, anh <strong>Hoàng N.Trung</strong> chia sẻ: <i><strong>“Pisen Mini Power rất tiện, nhỏ nhưng đủ dùng. Một thương hiệu lâu đời nên rất yên tâm về chất lượng.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>Pisen</strong> &nbsp; &nbsp; &nbsp;Model: <strong>Mini Power</strong> &nbsp; &nbsp; &nbsp;Dung lượng: <strong>10.000 mAh</strong></p>\r\n', 1),
(17, 17, 'Sạc Dự Phòng Không Dây MagSafe 10.000Mah', 'sacduphong4.jpg', 120, 0, 269000, 359000, '2025-05-08 23:12:48', 10, '<p><strong>Dành riêng cho iPhone và người dùng yêu thích sự gọn gàng – sạc dự phòng MagSafe 10.000mAh là sự lựa chọn cực kỳ thông minh.</strong></p>\r\n<p>Với công nghệ sạc không dây chuẩn MagSafe, thiết bị có thể hít chặt vào mặt lưng iPhone dòng 12 trở lên mà không cần cáp. Thiết kế nhỏ gọn, hiện đại và dung lượng 10.000mAh giúp người dùng thoải mái sử dụng cả ngày dài. Ngoài sạc không dây, còn hỗ trợ sạc nhanh có dây qua cổng Type-C.</p>\r\n<p>Chuyên gia công nghệ <strong>Hoàng N.Trung</strong> chia sẻ: <i><strong>“Sạc không dây MagSafe là phụ kiện phải có cho ai dùng iPhone – gọn nhẹ, tiện lợi và rất thời trang.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>Khác</strong> &nbsp; &nbsp; &nbsp;Loại: <strong>Sạc không dây MagSafe</strong> &nbsp; &nbsp; &nbsp;Dung lượng: <strong>10.000 mAh</strong></p>\r\n', 1),
(18, 6, 'Laptop MSI Modern 15 B13M-438VN', 'laptop4.jpg', 40, 0, 19670000, 15990000, '2025-05-08 23:20:33', 20, '<p><strong>MSI Modern 15 B13M-438VN là mẫu laptop mỏng nhẹ dành cho người dùng văn phòng, sinh viên cần hiệu suất ổn định và thiết kế hiện đại.</strong></p>\r\n<p>Trang bị vi xử lý Intel Core i5-1335U thế hệ mới, RAM 8GB và SSD 512GB giúp máy khởi động nhanh, đa nhiệm tốt. Máy có trọng lượng nhẹ, chỉ khoảng 1.7kg – phù hợp cho người thường xuyên di chuyển. Giao diện Windows 11 thân thiện và bàn phím thoải mái hỗ trợ làm việc cả ngày.</p>\r\n', '<p>Hãng sản xuất: <strong>MSI</strong> &nbsp; &nbsp; &nbsp;Model: <strong>Modern 15 B13M-438VN</strong> &nbsp; &nbsp; &nbsp;CPU: <strong>Intel Core i5-1335U</strong></p>\r\n', 1),
(20, 16, 'Tai Bluetooth Remax W33', 'tainghe4.jpg', 45, 0, 212000, 212000, '2025-05-08 23:31:04', 30, '<p><strong>Remax W33 gây ấn tượng mạnh nhờ thiết kế độc đáo như chiếc máy ảnh mini cùng chất âm ổn định – là món phụ kiện thời trang thú vị.</strong></p>\r\n<p>W33 mang kiểu dáng sáng tạo, hộp sạc trông như một chiếc máy chụp hình nhỏ xinh, cực kỳ bắt mắt. Kết nối Bluetooth mượt mà, âm thanh rõ ràng, mic đàm thoại tốt. Đây là sự lựa chọn lý tưởng cho những ai yêu thích phụ kiện cá tính và khác biệt.</p>\r\n<p>Theo đánh giá của anh <strong>Vũ Công Minh</strong>: <i><strong>“W33 không chỉ là tai nghe mà còn là món đồ cá nhân đầy phong cách – phù hợp giới trẻ thích độc lạ.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>Remax</strong> &nbsp; &nbsp; &nbsp;Model: <strong>W33</strong> &nbsp; &nbsp; &nbsp;Thiết kế: <strong>Hình máy chụp hình</strong></p>\r\n', 1),
(21, 6, 'Laptop Dell Inspiron 15 7501', 'laptop3.jpg', 20, 0, 17500000, 16500000, '2025-05-08 09:54:06', 30, '<p><strong>Dell Inspiron 15 7501 là chiếc laptop văn phòng cao cấp với thiết kế sang trọng, cấu hình ổn định và thời lượng pin dài.</strong></p>\r\n<p>Chiếc máy này nổi bật với vỏ kim loại chắc chắn, mỏng nhẹ nhưng vẫn trang bị màn hình lớn 15.6 inch Full HD sắc nét. Với bộ xử lý Intel thế hệ mới, ổ SSD tốc độ cao và pin bền, Dell Inspiron 7501 phục vụ tốt cho công việc văn phòng, học tập, chỉnh sửa ảnh nhẹ và giải trí cơ bản.</p>\r\n', '<p>Hãng sản xuất: <strong>Dell</strong> &nbsp; &nbsp; &nbsp;Model: <strong>Inspiron 15 7501</strong> &nbsp; &nbsp; &nbsp;Màn hình: <strong>15.6 inch</strong></p>\r\n', 1),
(23, 6, 'Laptop Lenovo Legion Pro 5 Y9000P (Core i9-14900HX)', 'laptop2.jpeg', 30, 0, 39500000, 37500000, '2025-05-08 12:19:16', 10, '<p><strong>Lenovo Legion Pro 5 Y9000P là cỗ máy chiến game cực mạnh với CPU Intel Core i9 đời 14, phù hợp cho game thủ và người làm đồ họa chuyên nghiệp.</strong></p>\r\n<p>Với chip Core i9-14900HX, dòng chip cao cấp nhất trong dòng laptop hiệu năng cao của Intel, sản phẩm xử lý mượt các tác vụ nặng như render video 4K, chơi game AAA, lập trình AI,… Cùng hệ thống tản nhiệt ColdFront 5.0 tối ưu, bàn phím RGB bắt mắt và màn hình chuẩn gaming giúp trải nghiệm cực kỳ chuyên nghiệp.</p>\r\n', '<p>Hãng sản xuất: <strong>Lenovo</strong> &nbsp; &nbsp; &nbsp;Model: <strong>Legion Pro 5 Y9000P</strong> &nbsp; &nbsp; &nbsp;CPU: <strong>Intel Core i9-14900HX</strong></p>\r\n', 1),
(24, 6, 'Laptop HP Gaming Victus 16-d1193TX 7C138P (i5/8GB/16\'\'/W11)', 'laptop1.jpg', 20, 0, 25000000, 22400000, '2025-05-08 12:20:16', 20, '<p><strong>HP Victus 16-d1193TX là mẫu laptop gaming tầm trung có thiết kế cứng cáp, cấu hình mạnh mẽ đáp ứng tốt cả chơi game và làm việc sáng tạo.</strong></p>\r\n<p>Máy trang bị chip Intel Core i5 thế hệ 11, RAM 8GB, card đồ họa rời NVIDIA GeForce GTX cho trải nghiệm mượt mà trong các tựa game phổ biến như Valorant, CS:GO, LOL,… Màn hình lớn 16 inch Full HD cho không gian hiển thị rộng rãi, tần số quét cao giúp hiển thị hình ảnh mượt. Hệ thống tản nhiệt hiện đại giúp máy luôn ổn định khi xử lý tác vụ nặng.</p>\r\n', '<p>Hãng sản xuất: <strong>HP</strong> &nbsp; &nbsp; &nbsp;Model: <strong>Victus 16-d1193TX</strong> &nbsp; &nbsp; &nbsp;CPU: <strong>Intel Core i5</strong> &nbsp; &nbsp; &nbsp;Màn hình: <strong>16 inch</strong></p>\r\n', 1),
(25, 16, 'Tai nghe Bluetooth Itel IEB-33 Đen', 'tainghe3.jpg', 50, 0, 299000, 199000, '2025-05-08 16:21:03', 6, '<p><strong>Itel IEB-33 là lựa chọn lý tưởng cho người dùng phổ thông cần một chiếc tai nghe Bluetooth giá rẻ nhưng đầy đủ tính năng cơ bản.</strong></p>\r\n<p>Sản phẩm có thiết kế gọn nhẹ, màu đen hiện đại, phù hợp với nhiều đối tượng người dùng. Kết nối Bluetooth ổn định, điều khiển cảm ứng dễ sử dụng, thời lượng pin khoảng 3-4 giờ cho mỗi lần sạc và có hộp sạc kèm theo.</p>\r\n<p>Trong buổi chia sẻ “Chọn tai nghe cho học sinh – sinh viên”, anh <strong>Hoàng N.Trung</strong> nhận xét: <i><strong>“Itel IEB-33 không nổi bật nhưng rất phù hợp cho nhu cầu nghe nhạc cơ bản, học online hay gọi video.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>Itel</strong> &nbsp; &nbsp; &nbsp;Model: <strong>IEB-33</strong> &nbsp; &nbsp; &nbsp;Màu sắc: <strong>Đen</strong></p>\r\n', 1),
(26, 2, 'OPPO A60 8GB|128GB', 'oppo2.png', 40, 0, 5690000, 4790000, '2025-05-08 16:23:55', 16, '<p><strong>Nếu bạn cần một chiếc điện thoại bền bỉ, thiết kế trẻ trung và hiệu năng ổn định thì OPPO A60 chính là sự lựa chọn lý tưởng.</strong></p>\r\n<p>OPPO A60 sở hữu bộ nhớ 8GB RAM cùng 128GB ROM, giúp thao tác đa nhiệm mượt mà và lưu trữ thoải mái. Máy được trang bị màn hình 6.67 inch siêu sáng 950 nits, cùng chuẩn độ bền quân đội Mỹ (MIL-STD-810H) chống va đập cực tốt. Thêm vào đó là viên pin lớn 5.000mAh cùng sạc nhanh SUPERVOOC 45W, cho trải nghiệm sử dụng suốt cả ngày dài.</p>\r\n<p>Trong buổi đánh giá “Smartphone cho sinh viên và người đi làm”, anh <strong>Nguyễn Thế Anh</strong> chia sẻ: <i><strong>“OPPO A60 là chiếc máy đáng tiền ở phân khúc tầm trung – đẹp, bền, pin khỏe, rất phù hợp cho ai cần dùng điện thoại bền bỉ và hiệu quả.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>OPPO</strong> &nbsp; &nbsp; &nbsp;Model: <strong>A60</strong> &nbsp; &nbsp; &nbsp;Dung lượng RAM/Bộ nhớ: <strong>8GB/128GB</strong></p>\r\n', 1),
(27, 2, 'Samsung Galaxy S23 FE 128GB', 'samsung3.jpg', 28, 2, 15990000, 14490000, '2025-05-08 20:31:17', 3, '<p><strong>Nếu bạn yêu thích dòng Galaxy S cao cấp nhưng lại muốn tiết kiệm ngân sách thì Galaxy S23 FE chính là lựa chọn lý tưởng.</strong></p>\r\n<p>Với thiết kế hiện đại và chất liệu cao cấp, Galaxy S23 FE mang trong mình sức mạnh của chip Exynos 2200 cùng bộ nhớ 128GB, màn hình AMOLED 120Hz và hệ thống camera được kế thừa từ dòng S23. Mọi trải nghiệm đều mượt mà, từ chơi game đến chụp ảnh hay quay video.</p>\r\n<p>Trong một buổi chia sẻ về “Smartphone Android cân bằng nhất trong tầm giá 10 triệu”, anh <strong>Hoàng N.Trung</strong> cho biết: <i><strong>“Galaxy S23 FE chính là bản rút gọn không thỏa hiệp của dòng S. Đây là chiếc máy giúp người dùng tiếp cận dòng cao cấp mà không cần bỏ ra quá nhiều tiền.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>Samsung</strong> &nbsp; &nbsp; &nbsp;Model: <strong>Galaxy S23 FE</strong> &nbsp; &nbsp; &nbsp;Màu sắc: <strong>Mint/Graphite/Tím</strong> &nbsp; &nbsp; &nbsp;Dung lượng: <strong>128GB</strong></p>\r\n', 1),
(28, 2, 'OPPO A58 8GB/128GB', 'oppo1.jpg', 60, 1, 5490000, 4590000, '2025-05-08 20:36:43', 13, '<p><strong>Nếu bạn đang tìm một chiếc điện thoại vừa có thiết kế đẹp, vừa hoạt động ổn định thì OPPO A58 là cái tên không thể bỏ qua.</strong></p>\r\n<p>OPPO A58 sở hữu màn hình lớn 6.72 inch FHD+, thiết kế mỏng nhẹ cùng vi xử lý Helio G85 kết hợp với 8GB RAM và bộ nhớ 128GB, giúp máy hoạt động mượt mà ở cả các tác vụ học tập, làm việc và giải trí. Camera 50MP mang lại khả năng chụp ảnh sắc nét trong nhiều điều kiện ánh sáng.</p>\r\n<p>Trong chia sẻ tại buổi “Chọn điện thoại dưới 5 triệu đáng mua nhất 2024”, anh <strong>Hoàng N.Trung</strong> nhận định: <i><strong>“A58 là một lựa chọn tốt cả về ngoại hình lẫn hiệu năng. Nếu bạn là người yêu thích thương hiệu OPPO thì đây là một lựa chọn rất đáng cân nhắc.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>OPPO</strong> &nbsp; &nbsp; &nbsp;Model: <strong>A58</strong> &nbsp; &nbsp; &nbsp;Màu sắc: <strong>Đen/Xanh</strong> &nbsp; &nbsp; &nbsp;Dung lượng: <strong>8GB/128GB</strong></p>\r\n', 1),
(29, 2, 'Realme C51 4GB|128GB', 'realmi.jpg', 30, 0, 3490000, 2890000, '2025-05-08 20:54:53', 13, '<p><strong>Nếu bạn nghĩ rằng smartphone giá rẻ sẽ luôn thiếu thốn tính năng thì có lẽ bạn nên nhìn lại với Realme C51.</strong></p>\r\n<p>Có thể bạn chưa biết, <strong>Realme C51</strong> là một trong những mẫu điện thoại phổ thông hiếm hoi có thiết kế hiện đại, màn hình lớn 6.7 inch, tần số quét 90Hz cùng viên pin 5000mAh tích hợp sạc nhanh 33W. Với RAM 4GB và bộ nhớ trong 128GB, thiết bị đáp ứng tốt nhu cầu học tập, giải trí và sử dụng hằng ngày.</p>\r\n<p>Anh <strong>Hoàng N.Trung</strong> (Section Manager - VEU) từng chia sẻ trong buổi nói chuyện “Smartphone giá rẻ đáng mua 2024” rằng: <i><strong>“C51 là chiếc máy cực kỳ hợp lý với học sinh – sinh viên, ai cần dùng app học tập, lướt web, xem video thì rất ổn.”</strong></i> Một lựa chọn tiết kiệm nhưng vẫn đầy đủ tiện ích đáng cân nhắc!</p>\r\n', '<p>Hãng sản xuất: <strong>Realme</strong> &nbsp; &nbsp; &nbsp;Model: <strong>C51</strong> &nbsp; &nbsp; &nbsp;Màu sắc: <strong>Xanh/Đen</strong> &nbsp; &nbsp; &nbsp;Dung lượng: <strong>4GB/128GB</strong></p>\r\n', 1),
(30, 2, 'Xiaomi 15 Ultra 512GB', 'xiaomi.jpg', 45, 0, 34990000, 32990000, '2025-05-08 20:56:21', 17, '<p><strong>Nếu bạn nghĩ chỉ iPhone hoặc Samsung mới có thể đứng ở đỉnh cao công nghệ thì Xiaomi 15 Ultra sẽ khiến bạn phải suy nghĩ lại.</strong></p>\r\n<p>Xiaomi 15 Ultra là siêu phẩm flagship mới nhất của Xiaomi, nổi bật với camera hàng đầu sử dụng cảm biến Sony LYT-900, màn hình AMOLED 2K 120Hz siêu sắc nét, chip Snapdragon 8 Gen 3 cùng bộ nhớ khủng 512GB. Thiết kế kim loại kết hợp mặt lưng cao cấp mang đến cảm giác sang trọng và chắc chắn.</p>\r\n<p>Trong buổi chia sẻ về “Flagship Android dẫn đầu công nghệ 2024”, anh <strong>Hoàng N.Trung</strong> nhận xét: <i><strong>“Xiaomi 15 Ultra là một siêu phẩm thực thụ – camera vượt trội, hiệu năng cực mạnh và trải nghiệm phần mềm đã được hoàn thiện rõ rệt.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>Xiaomi</strong> &nbsp; &nbsp; &nbsp;Model: <strong>15 Ultra</strong> &nbsp; &nbsp; &nbsp;Màu sắc: <strong>Đen/Trắng</strong> &nbsp; &nbsp; &nbsp;Dung lượng: <strong>512GB</strong></p>\r\n', 1),
(31, 16, 'Tai Nghe Bluetooth JBL', 'tainghe2.jpg', 29, 1, 420000, 350000, '2025-05-08 20:59:06', 26, '<p><strong>JBL luôn là thương hiệu được tin tưởng về chất lượng âm thanh và độ bền, đặc biệt trong phân khúc tai nghe không dây.</strong></p>\r\n<p>Với công nghệ âm thanh đặc trưng JBL Pure Bass, sản phẩm mang lại âm thanh sống động và đầy nội lực. Bluetooth thế hệ mới cho kết nối nhanh, ổn định. Thiết kế thể thao, pin dùng 4-6 giờ liên tục cùng hộp sạc tiện lợi.</p>\r\n<p>Chuyên gia âm thanh <strong>Nguyễn Văn Quý</strong> chia sẻ: <i><strong>“Dù là model nào, tai nghe JBL đều mang đến sự ổn định và trải nghiệm nghe nhạc tốt trong phân khúc giá.”</strong></i></p>\r\n', '<p>Hãng sản xuất: <strong>JBL</strong> &nbsp; &nbsp; &nbsp;Model: <strong>Không xác định</strong> &nbsp; &nbsp; &nbsp;Loại: <strong>Tai nghe Bluetooth</strong></p>\r\n', 1),
(32, 16, 'Tai nghe Bluetooth Soundpeats TrueFree Plus', 'tainghe1.jpg', 20, 0, 1290000, 999000, '2025-05-08 21:00:48', 64, '<p><strong>Soundpeats TrueFree Plus là mẫu tai nghe không dây chất lượng với âm thanh mạnh mẽ và thời lượng pin ấn tượng trong tầm giá.</strong></p><p>Sản phẩm sở hữu công nghệ Bluetooth 5.0 cho kết nối ổn định, độ trễ thấp. Chất âm cân bằng, bass tốt, thời lượng pin lên tới 35 giờ khi dùng kèm hộp sạc. Thiết kế nhỏ gọn, vừa tai, dễ sử dụng cho cả luyện tập thể thao hay đàm thoại.</p><p>Trong buổi trải nghiệm sản phẩm, anh <strong>Hoàng N.Trung</strong> nhận xét: <i><strong>“TrueFree Plus phù hợp với người dùng phổ thông muốn có tai nghe ổn định, pin lâu mà không cần chi quá nhiều.”</strong></i></p>', '<p>Hãng sản xuất: <strong>Soundpeats</strong> &nbsp; &nbsp; &nbsp;Model: <strong>TrueFree Plus</strong> &nbsp; &nbsp; &nbsp;Loại: <strong>Tai nghe Bluetooth True Wireless</strong></p>', 1),
(36, 2, 'iPhone 16 Pro Max', 'iphone16prm.jpg', 100, 0, 34990000, 30590000, '2025-06-04 00:50:31', 30, '<p>Iphone 16 là sản phẩm mới nhất</p>', '<p>Rất ok</p>', 1),
(37, 2, 'iPhone 16 Pro', 'iphone3.jpg', 100, 0, 34990000, 30590000, '2025-06-04 00:53:55', 3, '<p>ád</p>', '<p>ád</p>', 0),
(39, 2, 'Iphone XS Max', 'iphone2.jpg', 11, 1, 10000000, 9100000, '2025-06-04 11:32:27', 35, '<p>ádsad</p>', '<p>đâ</p>', 1),
(40, 16, 'Test', 'nokia.jpg', 10, 0, 10000000, 9000000, '2025-06-05 00:25:32', 13, '<p>qưeqw</p>', '<p>qưeqe</p>', 1),
(41, 16, 'Test1', 'iconzalo.svg', 10, 0, 10000000, 9000000, '2025-06-05 00:37:41', 3, '<p>ád</p>', '<p>dsa</p>', 1),
(42, 16, 'Test3', 'nokia.jpg', 9, 1, 10000000, 9000000, '2025-06-05 01:02:37', 39, '<p>á</p>', '<p>Á</p>', 1),
(43, 6, 'Test4', 'oppo1.jpg', 15, 0, 12000000, 11000000, '2025-06-05 12:42:57', 4, '<p>ád</p>', '<p>ád</p>', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`product_id`),
  ADD KEY `fk_category` (`category_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `product_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=44;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`category_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
